name: blind_view
description: "ShopEyes"

publish_to:

version: 1.0.0+1

environment:
  sdk: ^3.6.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  permission_handler: ^12.0.0+1
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  mobile_scanner: ^6.0.10
  shake: ^3.0.0
  voice_to_text: ^1.0.3
  shared_preferences: ^2.5.3
  flutter_tts: ^4.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
